name: Run Test

on: [push, pull_request]

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.WORKING_DIRECTORY }}/package.json

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install

      - name: Run tests
        working-directory: frontend
        run: npm test

  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t python-app -f backend/tests/Dockerfile ./backend

      - name: Run Pytest
        run: docker run python-app
